### ISSUE TITLE
Match error with [{:error, 'google.com', :nxdomain}]

### ISSUE THREAD

**Issue by tchoutri** [msantos/gen_icmp#10]
I'm having this error when my laptop doesn't resolve a domain name.

```
11:24:32.031 [error] GenServer #PID<0.304.0> terminating
** (MatchError) no match of right hand side value: [{:error, 'google.com', :nxdomain}]
    src/gen_icmp.erl:532: :gen_icmp."-addr_list0/3-lc$^2/1-0-"/2
    src/gen_icmp.erl:514: :gen_icmp.addr_list/4
    src/gen_icmp.erl:176: :gen_icmp.ping/3
    src/gen_icmp.erl:143: :gen_icmp.ping/2
    (nvjorn) lib/nvjorn/workers/icmp.ex:73: Nvjorn.Workers.ICMP.connect/1
    (nvjorn) lib/nvjorn/workers/icmp.ex:58: Nvjorn.Workers.ICMP.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
Last message: {:check, %Nvjorn.Services.ICMP{failure_count: 0, host: 'google.com', inet: 'inet', name: 'Google'}}
State: :ok
```

My own code looks like
```Elixir
result = :gen_icmp.ping(item.host, [List.to_atom(item.inet)])
```
So I don't think it could be an error from my side (although I may be wrong).

**Comment by msantos** [comment]
Thank you! Should be fixed now. If you run into any other issues, please let me know!
